/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ee_ut_ta_search_ged_NativeGed */

#ifndef _Included_ee_ut_ta_search_ged_NativeGed
#define _Included_ee_ut_ta_search_ged_NativeGed
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ee_ut_ta_search_ged_NativeGed
 * Method:    initializeStore
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ee_ut_ta_search_ged_NativeGed_initializeStore
  (JNIEnv *, jobject);

/*
 * Class:     ee_ut_ta_search_ged_NativeGed
 * Method:    finalizeStore
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ee_ut_ta_search_ged_NativeGed_finalizeStore
  (JNIEnv *, jobject);

/*
 * Class:     ee_ut_ta_search_ged_NativeGed
 * Method:    setSearchOptions
 * Signature: ([Z)V
 */
JNIEXPORT void JNICALL Java_ee_ut_ta_search_ged_NativeGed_setSearchOptions
  (JNIEnv *, jobject, jbooleanArray);

/*
 * Class:     ee_ut_ta_search_ged_NativeGed
 * Method:    setDictionaryContent
 * Signature: ([Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ee_ut_ta_search_ged_NativeGed_setDictionaryContent
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     ee_ut_ta_search_ged_NativeGed
 * Method:    setTransformationContent
 * Signature: ([Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ee_ut_ta_search_ged_NativeGed_setTransformationContent
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     ee_ut_ta_search_ged_NativeGed
 * Method:    process
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_ee_ut_ta_search_ged_NativeGed_process
  (JNIEnv *, jobject);

/*
 * Class:     ee_ut_ta_search_ged_NativeGed
 * Method:    setGedData
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_ee_ut_ta_search_ged_NativeGed_setGedData
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     ee_ut_ta_search_ged_NativeGed
 * Method:    setMaxEditDist
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_ee_ut_ta_search_ged_NativeGed_setMaxEditDist
  (JNIEnv *, jobject, jdouble);

#ifdef __cplusplus
}
#endif
#endif
