/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ee_ut_ta_search_SearchProcessor */

#ifndef _Included_ee_ut_ta_search_SearchProcessor
#define _Included_ee_ut_ta_search_SearchProcessor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ee_ut_ta_search_SearchProcessor
 * Method:    jniStoreWords
 * Signature: ([Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ee_ut_ta_search_SearchProcessor_jniStoreWords
  (JNIEnv *, jclass, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
